device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar100'
num_classes: 100
input_height: 
input_width:
input_channel:

epochs: 10
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR


model: 'preactresnet18'
random_seed: 0
index: 
alpha: 0.03
eps: 0.06
steps: 1
ratio: 0.1

